# Generated by Django 5.0.6 on 2024-07-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('libraryapp', '0003_remove_libraryusermodel_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryUserModel',
        ),
    ]
